# Generated by Django 2.1.4 on 2020-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_css2_css3_css4_css5_django1_django2_django3_django4_django5_js1_js2_js3_js4_js5_vue1_vue2_vue3_vue4_'),
    ]

    operations = [
        migrations.AddField(
            model_name='html2',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='html3',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='html4',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
