# Generated by Django 2.1.4 on 2020-05-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='quizname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Html2'),
        ),
    ]
