# Generated by Django 2.1.4 on 2020-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_results_quizname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
